### ISSUE TITLE
links中设置数组超过50个后无效？

### ISSUE THREAD

**Issue by glovanni** [xiedajian/relation-chart#3]
人物一共有400多个，关系是360个，但发现设置后无效。
links中的数组删到49个的时候，html页面才能显示，超过后页面无任何内容。
问题处在哪儿

**Comment by xiedajian** [comment]
看下控制台是否报错，检查数据标点符号是否有误

**Comment by glovanni** [comment]
> 看下控制台是否报错，检查数据标点符号是否有误

已经找到原因了，是我代码的问题，索引越界
