### ISSUE TITLE
你好，发现vue中暴力清除后再次实例化图片显示问题

### ISSUE THREAD

**Issue by supuwoerc** [xiedajian/relation-chart#6]
你好，如题，由于是动态数据，关系图需要多次加载数据，每次调用 new RelationChart方法前我将DOM元素内容清空，实例化可行，但是图片显示不出了，请问是什么原因 =。=||

**Comment by supuwoerc** [comment]
是节点的头像图片。

**Comment by supuwoerc** [comment]
已经找到了实现的方法：  d3.selectAll("svg").remove(); // 移除svg节点

我在dist里面添加的构造方法里面追加了这行代码，解决了问题，希望作者大大也能添加下，或是别的更好的方法。

**Comment by baozi-lala** [comment]
> 已经找到了实现的方法： d3.selectAll("svg").remove(); // 移除svg节点
> 
> 我在dist里面添加的构造方法里面追加了这行代码，解决了问题，希望作者大大也能添加下，或是别的更好的方法。

请问是加载哪里的
